### ISSUE TITLE
Reviews to be noted & feof() usage

### ISSUE THREAD

**Issue by GeoB99** [arnavbhatt288/cli-text-creator-reader#1]
I've left a comment [in the commit](https://github.com/arnavbhatt288/cli-text-creator-reader/commit/42f5ca0b803c24e3ef689ab565f6dfe491787d8c), be sure to check it.

Besides I'm quite skeptical about how you use `feof()`. It is not always guaranteed that the stream (a file in our case) will reach end of file. Since EOF is just a mere constant flag, the flag is set to the stream if there was a read error or we really reached the end of file. According to TutorialsPoint:
>  function returns a non-zero value when End-of-File indicator associated with the stream is set, else zero is returned.

Which means that the EOF indicator is set by whatever function it returns on termination, such as `fgetc()` and so forth.

**Comment by abt2804** [comment]
Alright, I can understand the problem. Maybe I would have to create something which will look for corruption of text files.
This program is concept though, I don't think it will ever gonna be perfect unless I would make myself perfect.

**Comment by abt2804** [comment]
For now, I am closing this issue but thanks btw.
